# -*- coding: utf-8 -*-
"""093-rock-euclidean - Rock style / CONCRETE layer:
Method 012 Euclidean Groove Locking (Bjorklund)  ->  generators.rhythm.euclidian

Phase 1: raw generative draft (single voice).
  Rhythm = the engine's Euclidean interval sequence euclidian(k, n) mapped to a
  FRACTIONAL tick unit (417/418 ticks -- deliberately NOT a 16th/8th multiple),
  so the raw draft is OFF-GRID by construction (the phase-1 fingerprint).
  Pitch  = unquantized seeded random walk (no scale snap, no chord tones,
  no harmony, no other voices).

Phase 2: musicom rules post-process (the method's LOCK + the rules layer):
  1. 16th-grid lock (078 mandatory rule): every Euclidean onset is placed on a
     16th (120) or 8th (240) unit -> 0 off-grid onsets.
  2. E-aeolian scale snap -> chord-tone quantize per bar, routed through the
     canonical Scale7ChordDegree.get_diatonic_note helper (no `% 7` wrappers).
  3. Voice-leading check/correction (rules.voice_leading) on the outer voices.
  4. Full 6-voice rock texture whose EVERY rhythm part is derived from a
     Euclidean pattern generated by generators.rhythm.euclidian.

Engine only: structures + workflows.unitmatrix_composer + generators.rhythm
+ rules.progression + rules.voice_leading. mido is imported READ-ONLY in the
audit/summary scripts (never for authoring).
"""
import itertools
import json
import os
import sys

import numpy as np

from structures import MusicUnit, MusicEvent
from workflows.unitmatrix_composer import (
    UnitMatrixComposer, create_empty_unit,
)
from generators.rhythm import euclidian          # method 012 implementation
from rules.progression import Scale7ChordDegree  # canonical diatonic helper
from rules.voice_leading import VoiceLeadingRules

# instrument registry (source of truth -- NOT pip-installed)
INSTR_DIR = "/opt/data/repos/musicom/projects/Instruments"
if INSTR_DIR not in sys.path:
    sys.path.insert(0, INSTR_DIR)
from instrument_registry import (  # noqa: E402
    FIDDLE, ACOUSTIC_GUITAR, PIANO, ORGAN, DOUBLE_BASS, DRUM_KIT,
)
from Percussion.drum_kit.drum_kit import KIT  # noqa: E402

SEED = 20260911
rng = np.random.default_rng(SEED)

# ---------------------------------------------------------------- project dirs
PROJ = ("/opt/data/repos/musicom/projects/Styles/Rock/"
        "093-rock-euclidean")
MIDI_DIR = os.path.join(PROJ, "MIDI")
AUDIO_DIR = os.path.join(PROJ, "Audio")
ANALYSIS_DIR = os.path.join(PROJ, "Analysis")
SCRIPTS_DIR = os.path.join(PROJ, "Scripts")
for d in (MIDI_DIR, AUDIO_DIR, ANALYSIS_DIR, SCRIPTS_DIR):
    os.makedirs(d, exist_ok=True)

# ---------------------------------------------------------------- concept
BPM = 128
TPB = 480
BEATS = 4
BAR = TPB * BEATS            # 1920
GRID16 = 120                 # 16th grid @ 480 TPB
GRID8 = 240                  # 8th grid
SECTION_TICKS = BAR * 4      # 7680 (4 bars per section)
NAMES = ["Intro", "Verse", "Chorus", "Bridge", "Chorus2", "Outro"]
BARS_PER = 4
N_SECTIONS = len(NAMES)
N_BARS = N_SECTIONS * BARS_PER          # 24

# E aeolian (natural minor): E F# G A B C D ; key root = E4 (MIDI 64)
KEY_ROOT = 64
AEOLIAN = [0, 2, 3, 5, 7, 8, 10]
SCALE_PCS = {(KEY_ROOT + i) % 12 for i in AEOLIAN}     # {4,6,7,9,11,0,2}
SCALE_PITCHES = [p for p in range(36, 97) if p % 12 in SCALE_PCS]


def degree_note(d):
    """Canonical diatonic note (no local % 7 wrapper)."""
    return Scale7ChordDegree.get_diatonic_note(KEY_ROOT, AEOLIAN, d)


def degree_pc(d):
    return degree_note(d) % 12


def degree_triad_pcs(d):
    return {degree_note(d + k) % 12 for k in (0, 2, 4)}


# 24-bar rock progression, 0-based scale degrees, all diatonic to E aeolian:
#   Intro   i  i  VI VII | Verse  i VI III VII | Chorus VI VII i  i
#   Bridge  iv VI III VII| Chorus2 VI VII i  i| Outro  i  i  VI i
PROG_DEG = ([0, 0, 5, 6] + [0, 5, 2, 6] + [5, 6, 0, 0] +
            [3, 5, 2, 6] + [5, 6, 0, 0] + [0, 0, 5, 0])
assert len(PROG_DEG) == N_BARS, (len(PROG_DEG), N_BARS)
DEG_NAME = {0: "i", 1: "ii", 2: "III", 3: "iv", 4: "v", 5: "VI", 6: "VII"}
PC_NAME = {4: "E", 6: "F#", 7: "G", 9: "A", 11: "B", 0: "C", 2: "D"}
BAR_LABELS = [PC_NAME[degree_pc(d)] + DEG_NAME[d] for d in PROG_DEG]


def chord_tones(deg, lo, hi):
    """Chord tones (diatonic triad) of degree `deg` inside [lo, hi]."""
    pcs = degree_triad_pcs(deg)
    return sorted(p for p in range(lo, hi + 1) if p % 12 in pcs)


def nearest_pc_pitch(pc, lo, hi, anchor=None):
    cands = [p for p in range(lo, hi + 1) if p % 12 == pc]
    if not cands:
        return None
    if anchor is None:
        return min(cands, key=lambda p: (abs(p - (lo + hi) // 2), p))
    return min(cands, key=lambda p: (abs(p - anchor), p))


# ---------------------------------------------------------------- method 012
def euclid_onsets(k, n, unit, rot=0):
    """Onset ticks inside ONE metric cycle (method 012, engine generator).

    The interval list comes straight from `generators.rhythm.euclidian`
    (the registry implementation of method 012); positions are the cumulative
    sums of those intervals, rotated by `rot` steps. `unit` is the tick value
    of one step. Cycle length is sum(intervals) * unit ticks.
    """
    ivs = euclidian(k, n)
    pos, t = [], 0
    for i in ivs:
        pos.append(t)
        t += i
    total = t
    ons = sorted({((p + rot) % total) * unit for p in pos})
    return ons, total * unit


# every Euclidean pattern used in phase 2, and the metric it locks to
#   (label) -> (k, n, step_ticks) ; assert step*sum(intervals) == BAR
PATTERNS = {
    "lead":   (6, 16, GRID16),   # 0 360 720 1080 1440  (syncopated 16th lock)
    "guitar": (4, 16, GRID16),   # 0 480 960 1440       (quarter-note chank)
    "piano":  (3, 8,  GRID8),    # 0 720 1440           (offbeat stabs)
    "bass":   (8, 8,  GRID8),    # 0 240 ... 1680       (8th-note drive)
    "kick":   (4, 16, GRID16),   # 0 480 960 1440
    "snare":  (2, 8,  GRID8),    # rotated -> 480 1440  (backbeat)
    "hat":    (8, 16, GRID16),   # 0 240 ... 1680       (8ths)
    "organ":  (1, 4,  TPB),      # 0                    (whole-bar sustain)
}
for _lbl, (_k, _n, _u) in PATTERNS.items():
    _ons, _cyc = euclid_onsets(_k, _n, _u)
    assert _cyc == BAR, (_lbl, _k, _n, _u, _cyc)
    assert all(o % GRID16 == 0 for o in _ons), (_lbl, _ons)


# ---------------------------------------------------------------- phase 1
P1_PAIRS = [(6, 16), (3, 8), (4, 16), (7, 16), (2, 8)]
UNIT1 = 417          # deliberately NOT a 16th (120) or 8th (240) multiple
P1_N = {0: 26, 1: 34, 2: 40, 3: 34, 4: 40, 5: 26}
P1_C = {0: 74.0, 1: 76.0, 2: 78.0, 3: 77.0, 4: 78.0, 5: 74.0}


def raw_euclid_melody(seed, section_ticks, n_events, center0):
    """Raw draft: Euclidean intervals at a FRACTIONAL unit + an unwalked pitch.

    The interval list comes from `euclidian(k, n)`; the tick value of one step
    is solved from the section length so the pattern fills the span, then
    jittered per onset. The resulting unit is almost never a multiple of 120,
    so the raw draft is off-grid by construction.
    """
    r = np.random.default_rng(seed)
    k, n = P1_PAIRS[seed % len(P1_PAIRS)]
    ivs = euclidian(k, n)
    cycle_steps = sum(ivs)
    # steps needed to fill the section: unit = section / total_pattern_steps
    unit = section_ticks / float(cycle_steps * max(1, n_events / cycle_steps))
    evs = []
    tick = 0.0
    center = center0
    i = 0
    while len(evs) < n_events:
        d = ivs[i % len(ivs)]
        step = unit * d * (0.94 + 0.12 * r.random())   # jitter -> OFF-GRID
        dur = int(round(step)) - 47                    # gaps -> no legato lock
        dur = max(60, dur)
        if tick + step > section_ticks:
            break
        # raw, unquantized pitch walk (no scale, no chord, no harmony)
        p = center + r.choice([-5, -3, -2, -1, 1, 2, 3, 4, 7]) + \
            0.9 * r.normal(0, 1.0)
        p = max(55.0, min(96.0, p))
        vel = int(np.clip(66 + 24 * abs(np.sin(i * 1.13)), 50, 108))
        evs.append(MusicEvent(pitch=int(round(p)), volume=vel,
                              start_tick=int(round(tick)),
                              end_tick=int(round(tick)) + dur))
        tick += step
        center += r.normal(0.0, 0.9)
        i += 1
    return evs


phase1 = UnitMatrixComposer(bpm=BPM, ticks_per_beat=TPB, beats_per_bar=BEATS)
phase1.create_matrix(num_voices=1, num_sections=N_SECTIONS)
phase1.add_voice("LeadRaw", program=FIDDLE.midi_program, channel=0)

for s, name in enumerate(NAMES):
    phase1.add_section(name, bars=BARS_PER)
    evs = raw_euclid_melody(SEED + s, SECTION_TICKS, P1_N[s], P1_C[s])
    if not evs or evs[-1].end_tick < SECTION_TICKS:
        evs.append(MusicEvent(pitch=0, volume=0,
                              start_tick=SECTION_TICKS - 1,
                              end_tick=SECTION_TICKS))
    phase1.set_unit(0, s, MusicUnit(events=evs))

ok1, msg1 = phase1.validate()
print("PHASE1 validate:", ok1, msg1)
assert ok1, msg1
P1_MIDI = os.path.join(MIDI_DIR, "093-rock-euclidean-phase1.mid")
phase1.to_midi(P1_MIDI)
print("phase1 written", P1_MIDI, os.path.getsize(P1_MIDI), "bytes")

# ---------------------------------------------------------------- phase 2
VOICES = [
    ("Lead",   FIDDLE.midi_program,          0),   # Fiddle (rock lead)
    ("Guitar", ACOUSTIC_GUITAR.midi_program, 1),   # Acoustic guitar (chank)
    ("Piano",  PIANO.midi_program,           2),   # Piano (offbeat stabs)
    ("Organ",  ORGAN.midi_program,           3),   # Organ (sustained pad)
    ("Bass",   DOUBLE_BASS.midi_program,     4),   # Double bass (8th drive)
    ("Drums",  DRUM_KIT.midi_program,        9),   # GM kit (ch 9)
]
N_V = len(VOICES)

phase2 = UnitMatrixComposer(bpm=BPM, ticks_per_beat=TPB, beats_per_bar=BEATS)
phase2.create_matrix(num_voices=N_V, num_sections=N_SECTIONS)
for name, prog, ch in VOICES:
    phase2.add_voice(name, program=prog, channel=ch)
for n in NAMES:
    phase2.add_section(n, bars=BARS_PER)

LEAD_LO, LEAD_HI = 60, 96      # fiddle range 55-96, sweet 62-86
# rules-layer idiomatic rock-tune contour: mostly stepwise with a few 3rds/4ths,
# applied in SCALE-DEGREE steps over the E-aeolian pool (the Euclidean grid
# supplies ALL the rhythm; this supplies an idiomatic interval contour).
MOTIF_STEPS = [0, 1, 2, 1, -1, 0, 2, 3, -1, -2, 1, 0]
LEAD_POOL = [p for p in SCALE_PITCHES if LEAD_LO <= p <= LEAD_HI]
CENTER_IDX = min(range(len(LEAD_POOL)), key=lambda i: abs(LEAD_POOL[i] - 76))

# --- row 0 LEAD: Euclidean 16th lock (rotating cell) + scale-degree contour
for s in range(N_SECTIONS):
    k, n, unit = PATTERNS["lead"]
    evs = []
    raw = sorted((e for e in phase1.matrix.get_unit((0, s)).events
                  if e.pitch > 0), key=lambda e: e.start_tick)
    raw_mean = (float(np.mean([e.pitch for e in raw])) if raw else 76.0)
    lead_center = min(range(len(LEAD_POOL)),
                      key=lambda i: abs(LEAD_POOL[i] - raw_mean))
    gcount = 0
    for b in range(BARS_PER):
        t0 = b * BAR
        rot = (b + s) % 3                       # rotate the Euclidean cell
        ons, _ = euclid_onsets(k, n, unit, rot=rot)
        bar = s * BARS_PER + b
        deg = PROG_DEG[bar]
        tones = chord_tones(deg, LEAD_LO, LEAD_HI) or [degree_note(deg) + 24]
        for j, off in enumerate(ons):
            step = MOTIF_STEPS[(s * BARS_PER * 6 + gcount) % len(MOTIF_STEPS)]
            lead_center = max(0, min(len(LEAD_POOL) - 1, lead_center + step))
            p = LEAD_POOL[lead_center]
            qp = min(tones, key=lambda c: (abs(c - p), c))
            accent = 0 if off % 480 == 0 else (1 if off % 240 == 0 else 2)
            vel = (92, 82, 74)[accent]
            evs.append(MusicEvent(pitch=qp, volume=vel,
                                  start_tick=t0 + off, end_tick=t0 + off + 118))
            gcount += 1
    evs.sort(key=lambda e: e.start_tick)
    # voice leading: cap leaps > 10 semitones toward the nearest chord tone
    for i in range(1, len(evs)):
        if abs(evs[i].pitch - evs[i - 1].pitch) > 10:
            bar = s * BARS_PER + min(evs[i].start_tick // BAR, BARS_PER - 1)
            tones = chord_tones(PROG_DEG[bar], LEAD_LO, LEAD_HI)
            if tones:
                evs[i].pitch = min(tones, key=lambda c: (abs(c - evs[i - 1].pitch), c))
    for i in range(len(evs) - 1):               # monophonic legato
        if evs[i].end_tick > evs[i + 1].start_tick:
            evs[i].end_tick = evs[i + 1].start_tick
    phase2.set_unit(0, s, MusicUnit(events=evs))

# --- row 1 GUITAR: Euclidean quarter-note chank (root + fifth dyads)
for s in range(N_SECTIONS):
    k, n, unit = PATTERNS["guitar"]
    evs = []
    for b in range(BARS_PER):
        t0 = b * BAR
        deg = PROG_DEG[s * BARS_PER + b]
        tones = chord_tones(deg, 40, 84) or [52]
        root = min(tones, key=lambda c: abs(c - 52))
        pcs = degree_triad_pcs(deg)
        # dyad partner = chord tone a fifth/fourth above the root; fall back to
        # the nearest higher chord tone so the dyad stays 100% in-chord.
        cands = [t for t in tones if t > root and (t - root) % 12 in (7, 5)]
        if not cands:
            cands = [t for t in tones if t > root]
        if not cands:
            cands = [root]
        fifth = min(cands, key=lambda c: abs(c - (root + 7)))
        ons, _ = euclid_onsets(k, n, unit)
        for j, off in enumerate(ons):
            vel = 92 if off % 480 == 0 else 76
            evs.append(MusicEvent(pitch=root, volume=vel,
                                  start_tick=t0 + off, end_tick=t0 + off + 110))
            evs.append(MusicEvent(pitch=fifth, volume=vel - 8,
                                  start_tick=t0 + off, end_tick=t0 + off + 110))
    phase2.set_unit(1, s, MusicUnit(events=evs))

# --- row 2 PIANO: Euclidean offbeat stabs (E(3,8) lock, octave 4)
for s in range(N_SECTIONS):
    k, n, unit = PATTERNS["piano"]
    evs = []
    for b in range(BARS_PER):
        t0 = b * BAR
        deg = PROG_DEG[s * BARS_PER + b]
        tones = chord_tones(deg, 55, 79) or [64]
        ons, _ = euclid_onsets(k, n, unit, rot=(s + b) % 3)
        for j, off in enumerate(ons):
            p = tones[(j + b) % len(tones)]
            evs.append(MusicEvent(pitch=p, volume=62,
                                  start_tick=t0 + off, end_tick=t0 + off + 110))
    phase2.set_unit(2, s, MusicUnit(events=evs))

# --- row 3 ORGAN: whole-bar sustained triad (E(1,4) lock, 55-79)
for s in range(N_SECTIONS):
    k, n, unit = PATTERNS["organ"]
    evs = []
    for b in range(BARS_PER):
        t0 = b * BAR
        deg = PROG_DEG[s * BARS_PER + b]
        tones = chord_tones(deg, 55, 79) or [64]
        pad = tones[:3]
        for j, p in enumerate(pad):
            evs.append(MusicEvent(pitch=p, volume=44 + 4 * j,
                                  start_tick=t0, end_tick=t0 + BAR - 60))
    phase2.set_unit(3, s, MusicUnit(events=evs))

# --- row 4 BASS: Euclidean 8th-note drive (E(8,8)), root + octave
for s in range(N_SECTIONS):
    k, n, unit = PATTERNS["bass"]
    evs = []
    for b in range(BARS_PER):
        t0 = b * BAR
        deg = PROG_DEG[s * BARS_PER + b]
        root = nearest_pc_pitch(degree_pc(deg), 33, 50, anchor=40) or 40
        ons, _ = euclid_onsets(k, n, unit)
        for j, off in enumerate(ons):
            p = root if j % 2 == 0 else min(root + 12, 62)
            evs.append(MusicEvent(pitch=p,
                                  volume=94 if off % 480 == 0 else 78,
                                  start_tick=t0 + off, end_tick=t0 + off + 200))
    phase2.set_unit(4, s, MusicUnit(events=evs))

# --- row 5 DRUMS: Euclidean kit (kick E(4,16), snare E(2,8) rotated +2)
DRUM_PLAN = {
    0: dict(kick=104, snare=None, hat=58, crash=True),
    1: dict(kick=112, snare=92, hat=66, crash=False),
    2: dict(kick=118, snare=98, hat=72, crash=True),
    3: dict(kick=110, snare=90, hat=62, crash=True),
    4: dict(kick=118, snare=98, hat=72, crash=False),
    5: dict(kick=104, snare=None, hat=56, crash=True),
}
for s in range(N_SECTIONS):
    plan = DRUM_PLAN[s]
    kk, kn, ku = PATTERNS["kick"]
    sk, sn, su = PATTERNS["snare"]
    hk, hn, hu = PATTERNS["hat"]
    evs = []
    for b in range(BARS_PER):
        t0 = b * BAR
        for off in euclid_onsets(kk, kn, ku)[0]:          # kick
            evs.append(MusicEvent(pitch=KIT["kick"], volume=plan["kick"],
                                  start_tick=t0 + off, end_tick=t0 + off + 120))
        for off in euclid_onsets(hk, hn, hu)[0]:          # hats
            evs.append(MusicEvent(pitch=KIT["hat_closed"], volume=plan["hat"],
                                  start_tick=t0 + off, end_tick=t0 + off + 60))
        if plan["snare"] is not None:                     # snare (E(2,8) rot 2)
            for off in euclid_onsets(sk, sn, su, rot=2)[0]:
                evs.append(MusicEvent(pitch=KIT["snare"], volume=plan["snare"],
                                      start_tick=t0 + off, end_tick=t0 + off + 120))
        if plan["crash"] and b == 0:
            evs.append(MusicEvent(pitch=KIT["crash"], volume=98,
                                  start_tick=t0, end_tick=t0 + 240))
    phase2.set_unit(5, s, MusicUnit(events=evs))

# --- voice-leading check/correction (outer voices = bass + lead)
vlc = VoiceLeadingRules(style="classical")
vl_flags = []
for bar in range(N_BARS - 1):
    s, b = divmod(bar, BARS_PER)
    deg_a, deg_b = PROG_DEG[bar], PROG_DEG[bar + 1]
    bass_a = nearest_pc_pitch(degree_pc(deg_a), 33, 50, anchor=40) or 40
    bass_b = nearest_pc_pitch(degree_pc(deg_b), 33, 50, anchor=40) or 40
    s2, b2 = (s, b + 1) if b + 1 < BARS_PER else (s + 1, 0)
    if s2 >= N_SECTIONS:
        continue

    def bar_evs(sec, bb, row=0):
        u = phase2.matrix.get_unit((row, sec))
        return [e for e in u.events
                if e.pitch > 0 and bb * BAR <= e.start_tick < (bb + 1) * BAR]

    evs, evs_next = bar_evs(s, b), bar_evs(s2, b2)
    if evs and evs_next:
        viol = vlc.check_parallel_motion([bass_a, evs[0].pitch],
                                         [bass_b, evs_next[0].pitch])
        if viol:
            vl_flags.append((bar, "parallel", viol))
        hid = vlc.check_hidden_fifths([bass_a, evs[0].pitch],
                                      [bass_b, evs_next[0].pitch])
        if hid:
            vl_flags.append((bar, "hidden", hid))
print("VL flags (bass+lead, classical):", len(vl_flags))


def fix_outer_voice(bar_target):
    """Nudge the lead's first note of bar_target off a 5th/8ve with the bass."""
    s, b = divmod(bar_target, BARS_PER)
    u = phase2.matrix.get_unit((0, s))
    evs = list(u.events)
    target = None
    for e in evs:
        if e.pitch > 0 and b * BAR <= e.start_tick < (b + 1) * BAR:
            target = e
            break
    if target is None:
        return False
    tones = chord_tones(PROG_DEG[bar_target], LEAD_LO, LEAD_HI)
    bass = nearest_pc_pitch(degree_pc(PROG_DEG[bar_target]), 33, 50,
                            anchor=40) or 40
    cands = [t for t in tones if (t - bass) % 12 not in (0, 7)]
    cands = [t for t in cands if abs(t - target.pitch) <= 10]
    if not cands:
        return False
    target.pitch = min(cands, key=lambda c: (abs(c - target.pitch), c))
    phase2.set_unit(0, s, MusicUnit(events=evs))
    return True


n_fixed = 0
for (bar, _kind, _v) in list(vl_flags):
    if fix_outer_voice(bar + 1):
        n_fixed += 1
print("VL fixes applied:", n_fixed)


# --- normalize every cell to the exact section boundary (zero-drift invariant)
def normalize_cell(unit, total_ticks):
    evs = list(unit.events)
    for e in evs:
        if e.end_tick > total_ticks:
            e.end_tick = total_ticks
        if e.start_tick >= total_ticks:
            e.start_tick = total_ticks - 10
        if e.start_tick < 0:
            e.start_tick = 0
        if e.end_tick <= e.start_tick:
            e.end_tick = min(total_ticks, e.start_tick + 60)
    if not evs or evs[-1].end_tick < total_ticks:
        evs.append(MusicEvent(pitch=0, volume=0, start_tick=total_ticks - 1,
                              end_tick=total_ticks))
    return MusicUnit(events=sorted(evs, key=lambda e: (e.start_tick, e.pitch)))


for s in range(N_SECTIONS):
    for v in range(N_V):
        u = phase2.matrix.get_unit((v, s))
        if u is None:
            phase2.set_unit(v, s, create_empty_unit(SECTION_TICKS))
            continue
        phase2.set_unit(v, s, normalize_cell(u, SECTION_TICKS))

ok2, msg2 = phase2.validate()
print("PHASE2 validate:", ok2, msg2)
assert ok2, msg2
P2_MIDI = os.path.join(MIDI_DIR, "093-rock-euclidean.mid")
phase2.to_midi(P2_MIDI)
print("phase2 written", P2_MIDI, os.path.getsize(P2_MIDI), "bytes")

# --- provenance sidecars
from workflows.provenance import write_provenance, AI_ASSISTED  # noqa: E402
write_provenance(P1_MIDI, classification=AI_ASSISTED,
                 generator="generators.rhythm.euclidian (method 012)",
                 parameters={"phase": 1, "seed": SEED, "unit1_ticks": UNIT1,
                             "pairs": P1_PAIRS, "bpm": BPM, "key": "E aeolian",
                             "method": "012 Euclidean Groove Locking"},
                 notes="Raw Euclidean draft: euclidian() intervals at a "
                       "fractional (off-grid) tick unit + unquantized pitch "
                       "walk. Single voice, no harmony.")
write_provenance(P2_MIDI, classification=AI_ASSISTED,
                 generator="generators.rhythm.euclidian + musicom rules layer",
                 parameters={"phase": 2, "seed": SEED, "bpm": BPM,
                             "key": "E aeolian",
                             "grid": "16th (120 @ 480 TPB)",
                             "progression": BAR_LABELS,
                             "euclid_patterns": {k: list(v) for k, v in
                                                 PATTERNS.items()},
                             "method": "012 Euclidean Groove Locking + rules"})
print("DONE")

# --- canonical high-contrast UnitMatrix grid render
from visualization.grid import write_grid_visualization  # noqa: E402
write_grid_visualization(phase2.matrix,
                         os.path.join(ANALYSIS_DIR, "matrix_grid.txt"),
                         ticks_per_character=120, bpm=BPM,
                         mode="E aeolian / Euclidean")
print("matrix_grid.txt written")

# --- machine-readable concept record for the REPORT
with open(os.path.join(ANALYSIS_DIR, "concept.json"), "w") as f:
    json.dump({"project": "093-rock-euclidean", "genre": "Rock",
               "method": "012 Euclidean Groove Locking",
               "layer": "concrete", "seed": SEED, "bpm": BPM,
               "key": "E aeolian", "grid_16th": GRID16,
               "euclid_patterns": {k: list(v) for k, v in PATTERNS.items()},
               "phase1_unit_ticks": UNIT1,
               "progression": BAR_LABELS,
               "sections": NAMES,
               "voices": [v[0] for v in VOICES],
               "vl_flags": len(vl_flags), "vl_fixes": n_fixed}, f, indent=2)
print("concept.json written")
