"""Tonal network progression generator (promoted from ``research/network.py``,
``research/intervalnetwork.py``).

Encodes a repertoire of chord qualities (tonic, pre-dominant, dominant, modal
borrows, chromatic mediants) as **nodes**, and the voice-leading/functional
bonds between them as **weighted, directed edges**. Chord progressions are then
generated by a weighted random walk over the graph — the same idea as the
research ''chromatic interval network'', but formalized as a reusable generator
that emits real ``MusicUnit`` chords instead of a static NetworkX export.

Usage:
    from generators.tonal_network import TonalNetworkGenerator

    gen = TonalNetworkGenerator(root=60, tonic_quality='major')
    unit = gen.progression(num_chords=8, seed=5, duration_beats=1)
"""

from typing import Dict, List, Optional, Sequence, Tuple
from collections import defaultdict
import random

from structures.unit import MusicUnit, MusicEvent
from generators.base import MusicGenerator

# Chord qualities -> semitone offsets from root.
# Canonical table lives in rules/harmony.py; alias kept for back-compat.
from rules.harmony import QUALITY_INTERVALS as CHORD_QUALITY


class TonalNetworkGenerator(MusicGenerator):
    """Generate chord progressions by a weighted random walk on a tonal graph.

    The graph is built once (node = a {root, quality} pair), and each edge
    carries a weight derived from functional affinity (e.g. dominant→tonic
    weight 1.0, dominant→subdominant weight 0.1). Higher weights are taken more
    often; ``weights`` may be overridden at construction.
    """

    def __init__(
        self,
        root: int = 60,
        tonic_quality: str = 'major',
        weights: Optional[Dict[Tuple[str, str], float]] = None,
        seed: Optional[int] = None,
    ):
        super().__init__()
        self.root = root
        self.tonic_quality = tonic_quality
        self.seed = seed

        # Functional affinity: (from_role, to_role) -> weight.
        # Higher = more likely to be chosen from `from_role`.
        self.affinity: Dict[Tuple[str, str], float] = weights or {
            # Home / resolution
            ('tonic', 'tonic'): 0.3,
            ('tonic', 'pre_dominant'): 0.2,
            ('tonic', 'dominant'): 0.3,
            ('tonic', 'mediant'): 0.1,
            ('tonic', 'borrow'): 0.1,
            # Subdominant perspective
            ('pre_dominant', 'dominant'): 0.9,
            ('pre_dominant', 'subdominant'): 0.3,
            ('pre_dominant', 'tonic'): 0.2,
            ('pre_dominant', 'mediant'): 0.1,
            # Dominant motion
            ('dominant', 'tonic'): 0.95,
            ('dominant', 'subdominant'): 0.05,
            ('dominant', 'mediant'): 0.05,
            # Subdominant
            ('subdominant', 'pre_dominant'): 0.6,
            ('subdominant', 'tonic'): 0.3,
            ('subdominant', 'borrow'): 0.1,
            # Mediant / chromatic
            ('mediant', 'subdominant'): 0.5,
            ('mediant', 'pre_dominant'): 0.3,
            ('mediant', 'borrow'): 0.2,
            # Modal borrow
            ('borrow', 'subdominant'): 0.5,
            ('borrow', 'tonic'): 0.4,
            ('borrow', 'mediant'): 0.1,
        }
        self._rng = random.Random(seed)

        # Node catalog: role -> (root offset from tonic, quality)
        self.catalog: Dict[str, Tuple[int, str]] = self._build_catalog(tonic_quality)
        # Inverse map role -> node index for adjacency bookkeeping
        self._roles = list(self.catalog.keys())

    @staticmethod
    def _build_catalog(tonic_quality: str) -> Dict[str, Tuple[int, str]]:
        """Define the tonal regions relative to the tonic root (offset 0)."""
        cat: Dict[str, Tuple[int, str]] = {
            'tonic': (0, tonic_quality),
            'subdominant': (5, 'major') if tonic_quality != 'minor' else (5, 'minor'),
            'dominant': (7, 'major') if tonic_quality != 'minor' else (7, 'major'),
            'mediant': (4, 'minor'),     # iii
            'pre_dominant': (2, 'minor'),  # ii
            'borrow': (10, 'major'),     # bVII (backdoor / Mixolydian borrow)
        }
        return cat

    # -- graph access ------------------------------------------------------

    @property
    def roles(self) -> List[str]:
        return self._roles

    def node_pitches(self, role: str) -> List[int]:
        """Absolute MIDI pitches of the chord for a role."""
        root_off, quality = self.catalog[role]
        tones = CHORD_QUALITY[quality]
        base = self.root + root_off
        # drop duplicate roots from seventh chords (register sanity between 52..84)
        return [base + t for t in tones]

    def transitions(self) -> Dict[str, List[Tuple[str, float]]]:
        """Return the adjacency table (role -> [(target_role, weight), ...])."""
        table: Dict[str, List[Tuple[str, float]]] = defaultdict(list)
        for (a, b), w in self.affinity.items():
            if a in self.catalog and b in self.catalog:
                table[a].append((b, w))
        return dict(table)

    # -- generation --------------------------------------------------------

    def _pick(self, from_role: str) -> str:
        """Weighted choice of next role from ``from_role``."""
        opts = self.transitions().get(from_role, [])
        if not opts:
            return 'tonic'
        roles = [t for t, _ in opts]
        weights = [w for _, w in opts]
        return self._rng.choices(roles, weights=weights, k=1)[0]

    def progression(
        self,
        num_chords: int = 8,
        duration_beats: float = 1.0,
        ticks_per_beat: int = 480,
        start_role: str = 'tonic',
        volume: int = 90,
    ) -> MusicUnit:
        """Generate a weighted random-walk chord progression as a ``MusicUnit``.

        Args:
            num_chords: number of chords in the walk (incl. the tonic start).
            duration_beats: note length of each chord (in beats).
            ticks_per_beat: tick resolution.
            start_role: first chord role (default tonic).
            volume: velocity for all chord tones.

        Returns:
            A ``MusicUnit``. Each chord occupies one consecutive beat-slots.
        """
        if num_chords < 1:
            raise ValueError("num_chords must be >= 1")
        roles = [start_role]
        while len(roles) < num_chords:
            roles.append(self._pick(roles[-1]))

        out = MusicUnit()
        dur = max(1, int(round(duration_beats * ticks_per_beat)))
        tick = 0
        for role in roles:
            for p in self.node_pitches(role):
                out.add_event(MusicEvent(
                    pitch=p, volume=volume,
                    start_tick=int(tick), end_tick=int(tick + dur),
                ))
            tick += dur
        return out

    # -- plain graph helpers (parity with research) ------------------------

    def progression_roles(self, num_chords: int = 8,
                          start_role: str = 'tonic') -> List[str]:
        """Return just the role sequence (no unit) — useful for tests/reporting."""
        roles = [start_role]
        while len(roles) < num_chords:
            roles.append(self._pick(roles[-1]))
        return roles

    def generate(self) -> List[MusicUnit]:
        """Concrete ``MusicGenerator.generate``: return a default progression."""
        return [self.progression(num_chords=8)]