# -*- coding: utf-8 -*-
"""091-baroque-genetic-allemande — Baroque style / CONCRETE layer:
Method 003 Genetic Genome Selection (GeneticGenerator) with a Bach-influenced
fitness function.

Phase 1: raw generative draft (single voice). The genetic algorithm's best
genome is decoded to raw events WITHOUT any scale/chord constraint: pitch
intervals and onset intervals come straight from the genome bits (off-grid
fingerprint, `binary_to_unit`'s `onset * 120` is *not* a 16th lock — onset
values 0..15 x 120 = 0..1800, so non-multiples of 120 appear). Chords are
completely absent (single voice, no harmony). Subject to the fitness push for
Bach-style contour (leaps < 5th, stepwise motion, arch shape).

Phase 2: musicom rules post-process:
  16th-grid lock (078 mandatory rule) -> D-minor scale snap -> chord-tone
  quantize per global bar (chord from the TonalNetworkGenerator walk
  [Method 011 wiring], which is the phase-2 harmonic scaffold) ->
  voice-leading check/correction (rules.voice_leading) -> full 7-voice
  Baroque texture (violin lead, oboe + cello counterlines, organ continuo,
  bass, optional viola, drums for body).

Engine only: structures + workflows.unitmatrix_composer + generators.genetic +
generators.tonal_network + rules.voice_leading. mido used READ-ONLY in audit.

The RAW phase-1 timeline is generated by a genetic-evolution drum machine
evolved with a Baroque fitness; the musicom rules layer then turns it into a
Baroque-idiomatic allemande (medium-slow 4/4 dance with 8th-note flow,
dotted-rhythm lift in Chorus, walking bass).
"""
import os
import sys
import json
import random

import numpy as np

from structures import MusicUnit, MusicEvent
from workflows.unitmatrix_composer import (
    UnitMatrixComposer, create_empty_unit,
)
from generators.genetic import (
    GeneticGenerator, generate_genome, selection_pair,
    single_point_crossover, mutation, genome_to_string, binary_to_unit,
)
from generators.tonal_network import TonalNetworkGenerator
from rules.voice_leading import VoiceLeadingRules

# instrument registry (source of truth - NOT pip-installed)
INSTR_DIR = "/opt/data/repos/musicom/projects/Instruments"
if INSTR_DIR not in sys.path:
    sys.path.insert(0, INSTR_DIR)
from instrument_registry import (  # noqa: E402
    VIOLIN, FLUTE, CELLO, PIANO, DOUBLE_BASS, DRUM_KIT, OBOE, VIOLA,
)

SEED = 20260909
rng = np.random.default_rng(SEED)

# ---------------------------------------------------------------- project dirs
PROJ = "/opt/data/repos/musicom/projects/Styles/Baroque/091-baroque-genetic-allemande"
MIDI_DIR = os.path.join(PROJ, "MIDI")
AUDIO_DIR = os.path.join(PROJ, "Audio")
ANALYSIS_DIR = os.path.join(PROJ, "Analysis")
for d in (MIDI_DIR, AUDIO_DIR, ANALYSIS_DIR):
    os.makedirs(d, exist_ok=True)

# ---------------------------------------------------------------- concept
BPM = 92
TPB = 480
BEATS = 4
BAR = TPB * BEATS            # 1920
GRID16 = 120                 # 16th-note grid @ 480 TPB
GRID8 = 240                  # 8th-note grid
SECTION_TICKS = BAR * 4      # 7680 (4 bars per section)

# D aeolian (natural minor) scale pitches across usable registers
SCALE = [38, 40, 41, 43, 45, 46, 48, 50, 52, 53, 55, 57, 58, 60, 62, 64, 65,
         67, 69, 70, 72, 74, 76, 77, 79, 81, 83, 84]
SCALE_PCS = {2, 4, 5, 7, 9, 11, 0}   # D E F G A Bb C

# ---------------------------------------------------------------- harmony
# Phase-2 harmonic scaffold: Method 011 TonalNetworkGenerator walk (D minor).
# This is a *trained* walk that gives a Baroque-flavored progression; the
# genetic raw draft in phase 1 knows nothing about it (two-phase separation).
# The walk emits **roles** ('tonic', 'dominant', ...); we decode each role to
# its chord tones via node_pitches and catalog, giving an explicit harmony
# per bar. The harmony is D-minor functional (i - iv - V - VI ...).
#
# NOTE (diatonic realization): the generator's minor-key catalog uses a
# chromatic mediant (F#m) and minor borrow (Fm) which introduce out-of-scale
# tones (F#, Ab). We keep the generator's ROLE WALK (method 011 output) but
# realize each role DIATONICALLY in D aeolian + harmonic-minor C#:
#   tonic i (Dm), subdominant iv (Gm), dominant V (A major, raised 3rd C#),
#   mediant III (F major), pre-dominant ii (Em), borrow bVII (C major).
# Keep the granularity of the walk, shed the chromatic mixture.
TONAL = TonalNetworkGenerator(root=50, tonic_quality="minor", seed=SEED)
ROLE_OFF = {"tonic": 0, "subdominant": 5, "dominant": 7, "mediant": 3,
            "pre_dominant": 2, "borrow": 10}
ROLE_Q = {"tonic": "m", "subdominant": "m", "dominant": "M", "mediant": "M",
          "pre_dominant": "m", "borrow": "M"}
# reproduce the weighted walk (seeded via roll-your-own rng for determinism)
_roles = ["tonic"]
_rng_tonal = random.Random(SEED)
while len(_roles) < 24:
    _roles.append(TONAL._pick(_roles[-1]))

CHORD_INFO = []
for role in _roles:
    root = 50 + ROLE_OFF[role]
    quality = ROLE_Q[role]
    CHORD_INFO.append((root, quality))
print("TONAL walk roles:", _roles)
print("CHORD_INFO:", [(r, q) for r, q in CHORD_INFO])

IV = {"m": (0, 3, 7), "M": (0, 4, 7), "d": (0, 3, 6), "7": (0, 4, 7, 10),
      "m7": (0, 3, 7, 10), "M7": (0, 4, 7, 11),
      "sus2": (0, 2, 7), "sus4": (0, 5, 7), "m7b5": (0, 3, 6, 10)}


def chord_pcs_of(root, quality):
    return set((root + i) % 12 for i in IV[quality])


def chord_tones(root, quality, lo, hi):
    tones = set()
    for oct_shift in range(-2, 5):
        for i in IV[quality]:
            p = root + i + oct_shift * 12
            if lo <= p <= hi:
                tones.add(p)
    return sorted(tones)


def quantize_to_chord(pitch, tones):
    return min(tones, key=lambda c: (abs(c - pitch), c))


def nearest_pc_pitch(pc, lo, hi, anchor=None):
    cands = [p for p in range(lo, hi + 1) if p % 12 == pc]
    if not cands:
        return None
    if anchor is None:
        return min(cands, key=lambda p: (abs(p - (lo + hi) // 2), p))
    return min(cands, key=lambda p: (abs(p - anchor), p))


NAMES = ["Intro", "AllemandeA", "AllemandeB", "Lift", "AllemandeA2", "Outro"]
BARS_PER = 4
N_SECTIONS = len(NAMES)
N_BARS = N_SECTIONS * BARS_PER            # 24

# Progression label per bar for REPORT (functional reading of TONAL walk)
TRIAD_LABEL = {"m": "m", "M": "", "d": "dim", "7": "7", "m7": "m7",
               "M7": "M7", "sus2": "sus2", "sus4": "sus4", "m7b5": "m7b5"}


def bar_label(root, quality):
    names = ["D", "Eb", "E", "F", "F#", "G", "Ab", "A", "Bb", "B", "C", "C#"]
    return names[root % 12] + TRIAD_LABEL[quality]


# ---------------------------------------------------------------- phase 1
# Genetic raw draft: evolve a genome whose decoded events become the raw
# timeline. Fitness rewards Baroque contour: stepwise motion, small leaps,
# arch shape, no long note-storms, 8th-note flow.
P1_LEN = 48          # 48 events * 18 bits each (6 pitch + 4 onset + 4 dur + 4 vel)
def baroque_fitness(genome):
    """Fitness for a genetic genome: reward Bach-style conjunct motion.
    Genome layout is the library's 18-bit event: pitch bits (0..5) per event
    decode to a RELATIVE interval; onset/dur/vel bits are irrelevant here.
    Consecutive stepwise intervals (streams) are rewarded super-linearly;
    big leaps are penalized."""
    s = 0
    n_ev = len(genome) // 18
    run = 0
    for i in range(n_ev):
        base = i * 18
        chunk = sum(bit * pow(2, j) for j, bit in enumerate(genome[base:base + 6]))
        interval = chunk % 24 - 12        # -12..+11 semitones
        if abs(interval) in (1, 2):       # stepwise
            run += 1
            s += 3 + run                  # streaks = Bach-style streams
        elif abs(interval) in (3, 4, 5):  # small leap
            run = 0
            s += 1
        elif abs(interval) == 0:          # repeat
            run = 0
            s += 0
        else:                             # large leap
            run = 0
            s -= 2
    return max(1, s)


GEN = GeneticGenerator(
    fitness_func=baroque_fitness,
    size=24,
    genome_length=P1_LEN * 18,     # 18 bits per event (6+4+4+4)
    fitness_limit=10**9,
    generation_limit=6,            # fast; keep raw character
    # seed handled by our own rng below
)
# Use the library's own population machinery via generate_population, then
# run a few generations manually so we can keep genealogy notes.
pop = GEN.generate_population()
for _g in range(GEN.generation_limit):
    pop = sorted(pop, key=lambda bg: GEN.fitness_func(bg), reverse=True)
    if GEN.fitness_func(pop[0]) >= GEN.fitness_limit:
        break
    nxt = pop[0:2]
    for j in range(int(len(pop) / 2) - 1):
        p1, p2 = selection_pair(pop, GEN.fitness_func)
        oa, ob = single_point_crossover(p1, p2)
        oa, ob = mutation(oa), mutation(ob)
        nxt += [oa, ob]
    pop = nxt
BEST = pop[0]
print("GA best fitness:", GEN.fitness_func(BEST))

# raw chronological events from the best genome
RAW_UNIT = binary_to_unit(BEST)
RAW_EVENTS = sorted(list(RAW_UNIT.events), key=lambda e: e.start_tick)
print("raw events:", len(RAW_EVENTS), "first starts:",
      [e.start_tick for e in RAW_EVENTS[:8]])
# raw timeline: the genome may run max 48*1800 ticks; we distribute across
# the full 24-bar form by wrapping the raw event stream (raw character in
# EVERY section, off-grid, unquantized, no harmony)

rng1 = np.random.default_rng(SEED + 1)   # for section fills (kept minimal)

phase1 = UnitMatrixComposer(bpm=BPM, ticks_per_beat=TPB, beats_per_bar=BEATS)
phase1.create_matrix(num_voices=1, num_sections=N_SECTIONS)
phase1.add_voice("LeadRaw", program=VIOLIN.midi_program, channel=0)

for s, name in enumerate(NAMES):
    evs = []
    # map raw events into this section: spread them by their relative timing
    if RAW_EVENTS:
        span = RAW_EVENTS[-1].end_tick or 1
        for e in RAW_EVENTS:
            frac = e.start_tick / span
            st = int(frac * (SECTION_TICKS - 200))
            dur = max(60, int(e.duration * 0.9))
            en = min(SECTION_TICKS, st + dur)
            # clamp into section, keep raw character (no grid snap!)
            st = max(0, min(st, SECTION_TICKS - 1))
            if en > st:
                evs.append(MusicEvent(pitch=e.pitch, volume=e.volume,
                                      start_tick=st, end_tick=en))
    # zero-drift landmark
    has_landmark = any(e.pitch == 0 and e.end_tick == SECTION_TICKS
                       for e in evs)
    if not has_landmark:
        evs.append(MusicEvent(pitch=0, volume=0,
                              start_tick=SECTION_TICKS - 1,
                              end_tick=SECTION_TICKS))
    phase1.add_section(name, bars=BARS_PER)
    phase1.set_unit(0, s, MusicUnit(events=evs))

ok1, msg1 = phase1.validate()
print("PHASE1 validate:", msg1)
P1_MIDI = os.path.join(MIDI_DIR, "091-baroque-genetic-allemande-phase1.mid")
phase1.to_midi(P1_MIDI)
print("phase1 written", P1_MIDI)

# ---------------------------------------------------------------- phase 2
def quantize_to_grid(events, grid=GRID16):
    q = []
    for e in events:
        if e.pitch == 0:
            q.append(e)
            continue
        st = int(round(e.start_tick / grid) * grid)
        q.append(MusicEvent(pitch=e.pitch, volume=e.volume,
                            start_tick=st, end_tick=max(st + 1, e.end_tick)))
    return q


phase2 = UnitMatrixComposer(bpm=BPM, ticks_per_beat=TPB, beats_per_bar=BEATS)
VOICES = [
    ("Lead",    VIOLIN.midi_program, 0),     # Violin (genetic lead)
    ("Oboe",    OBOE.midi_program, 1),       # Oboe (answering counterline)
    ("Cello",   CELLO.midi_program, 2),      # Cello (sustained pad / counter)
    ("Piano",   PIANO.midi_program, 3),      # Piano (continuo arpeggio)
    ("Viola",   VIOLA.midi_program, 4),      # Viola (inner harmony)
    ("Bass",    DOUBLE_BASS.midi_program, 5),# Double Bass (walking roots)
    ("Drums",   DRUM_KIT.midi_program, 9),   # percussion channel
]
N_V = len(VOICES)
phase2.create_matrix(num_voices=N_V, num_sections=N_SECTIONS)
for name, prog, ch in VOICES:
    phase2.add_voice(name, program=prog, channel=ch)
for n in NAMES:
    phase2.add_section(n, bars=BARS_PER)

# --- lead: GRID LOCK FIRST, then scale snap + chord-tone quantize (078 rule)
for s, name in enumerate(NAMES):
    raw_unit = phase1.matrix.get_unit((0, s))
    raw_events = quantize_to_grid(list(raw_unit.events), grid=GRID16)
    q_events = []
    for e in raw_events:
        if e.pitch == 0:
            q_events.append(e)
            continue
        # scale snap (D aeolian)
        sc = min(SCALE, key=lambda c: (abs(c - e.pitch), c))
        local_bar = min(e.start_tick // BAR, BARS_PER - 1)
        bar = s * BARS_PER + local_bar
        root, quality = CHORD_INFO[bar]
        tones = chord_tones(root, quality, lo=60, hi=88)   # violin register
        if not tones:
            tones = chord_tones(root, quality, lo=55, hi=84)
        qp = quantize_to_chord(sc, tones)
        q_events.append(MusicEvent(pitch=qp, volume=e.volume,
                                   start_tick=e.start_tick,
                                   end_tick=e.end_tick))
    # voice-leading: cap leaps <= 10 toward nearest chord tone of next event
    for i in range(1, len(q_events)):
        e = q_events[i]
        if e.pitch == 0:
            continue
        p_prev = q_events[i - 1].pitch if q_events[i - 1].pitch else 74
        if abs(e.pitch - p_prev) > 10:
            local_bar = min(e.start_tick // BAR, BARS_PER - 1)
            bar = s * BARS_PER + local_bar
            root, quality = CHORD_INFO[bar]
            tones = chord_tones(root, quality, lo=60, hi=88)
            if tones:
                e.pitch = min(tones, key=lambda c: (abs(c - p_prev), c))
    phase2.set_unit(0, s, MusicUnit(events=q_events))

# --- cello: sustained whole-bar pad (root-position triad shell)
for bar in range(N_BARS):
    s, b = divmod(bar, BARS_PER)
    root, quality = CHORD_INFO[bar]
    tones = [root, root + IV[quality][1], root + IV[quality][2]]
    tones = sorted(set(p for p in tones if 36 <= p <= 62))
    if not tones:
        tones = sorted(set((root + i) % 12 + 48 for i in IV[quality]))
    t0 = b * BAR
    e = []
    for k, p in enumerate(tones):
        e.append(MusicEvent(pitch=p, volume=46 + 4 * k,
                            start_tick=t0, end_tick=t0 + BAR - 60))
    unit = phase2.matrix.get_unit((2, s))
    events = list(unit.events) if unit is not None else []
    events.extend(e)
    phase2.set_unit(2, s, MusicUnit(events=events))

# --- oboe: 8th-note answering counterline (chord tones +12 window)
for s in range(N_SECTIONS):
    r = np.random.default_rng(SEED + 300 + s)
    evs = []
    for bar in range(BARS_PER):
        t0 = bar * BAR
        root, quality = CHORD_INFO[s * BARS_PER + bar]
        tones = [t for t in chord_tones(root, quality, lo=72, hi=88)]
        if not tones:
            tones = chord_tones(root, quality, lo=60, hi=76) or [72]
        # answers on beats 2 & 4 with 8th pickup into next beat
        for beat in (1, 3):
            st = t0 + beat * 480
            pitch = int(r.choice(tones))
            evs.append(MusicEvent(pitch=pitch, volume=62,
                                  start_tick=st, end_tick=st + 240))
            st2 = st + 240
            if st2 < t0 + BAR:
                pitch2 = int(r.choice(tones))
                evs.append(MusicEvent(pitch=pitch2, volume=56,
                                      start_tick=st2, end_tick=st2 + 240))
    phase2.set_unit(1, s, MusicUnit(events=evs))

# --- piano: continuo-style 16th arpeggio rolls (chord tones, octave 4/5)
for bar in range(N_BARS):
    s, b = divmod(bar, BARS_PER)
    root, quality = CHORD_INFO[bar]
    tones = chord_tones(root, quality, lo=60, hi=84)
    if not tones:
        tones = chord_tones(root, quality, lo=48, hi=72) or [60]
    t0 = b * BAR
    e = []
    n = len(tones)
    for k in range(0, BAR, 120):
        idx = (k // 120) % n
        p = tones[idx]
        e.append(MusicEvent(pitch=p, volume=54,
                            start_tick=t0 + k, end_tick=t0 + k + 80))
    unit = phase2.matrix.get_unit((3, s))
    events = list(unit.events) if unit is not None else []
    events.extend(e)
    phase2.set_unit(3, s, MusicUnit(events=events))

# --- viola: inner harmony — whole-bar chord tones (octave 3/4)
for bar in range(N_BARS):
    s, b = divmod(bar, BARS_PER)
    root, quality = CHORD_INFO[bar]
    tones = chord_tones(root, quality, lo=48, hi=67)
    if not tones:
        tones = [nearest_pc_pitch(root % 12, 48, 67) or 55]
    t0 = b * BAR
    e = []
    mid = tones[len(tones) // 2] if len(tones) > 2 else tones[0]
    e.append(MusicEvent(pitch=mid, volume=50,
                        start_tick=t0, end_tick=t0 + BAR - 60))
    unit = phase2.matrix.get_unit((4, s))
    events = list(unit.events) if unit is not None else []
    events.extend(e)
    phase2.set_unit(4, s, MusicUnit(events=events))

# --- bass: walking string-bass line. Root on 1, 8th-note walk through the
#     chord tones toward next root; 16th push into next bar in Lift.
BASS_8TH = {2, 4, 5}          # sections with 8th-note pulse
BASS_PUSH = {3}               # Lift: 16th push
BASS_DOTTED = {1, 2}          # dotted-rhythm lift (allemande ornament)
for bar in range(N_BARS):
    s, b = divmod(bar, BARS_PER)
    root, quality = CHORD_INFO[bar]
    root_pc = root % 12
    bass = nearest_pc_pitch(root_pc, 33, 52, anchor=41)
    if bass is None:
        bass = 41
    t0 = b * BAR
    e = []
    if s in BASS_8TH or s == 0:
        # walking 8ths: root + chord-tone neighbors
        tones = chord_tones(root, quality, lo=33, hi=52)
        if not tones:
            tones = [bass, bass + 3, bass + 7, bass + 12]
        # smooth walk: start on root, move within chord tones toward next bar
        for k in range(0, BAR, GRID8):
            on_beat = (k // GRID8) % 2 == 0
            if k == 0:
                p = bass
            else:
                # choose a chord tone near the previous pitch
                prev = e[-1].pitch if e else bass
                p = min(tones, key=lambda c: (abs(c - prev), c))
            e.append(MusicEvent(pitch=p, volume=78 if on_beat else 62,
                                start_tick=t0 + k, end_tick=t0 + k + 190))
    else:
        # quarters
        for k in range(0, BAR, 480):
            p = bass
            e.append(MusicEvent(pitch=p, volume=74,
                                start_tick=t0 + k, end_tick=t0 + k + 400))
    if s in BASS_PUSH and b != BARS_PER - 1:
        e.append(MusicEvent(pitch=bass, volume=70,
                            start_tick=t0 + BAR - 120, end_tick=t0 + BAR - 20))
    unit = phase2.matrix.get_unit((5, s))
    events = list(unit.events) if unit is not None else []
    events.extend(e)
    phase2.set_unit(5, s, MusicUnit(events=events))

# --- drums: Baroque-appropriate body (subtle). Intro sparse, A sections
#     courtly (kick 1&3, snare 2&4, 8th hats), Lift fuller, Outro sparse.
from Percussion.drum_kit.drum_kit import KIT  # noqa: E402
K = KIT
DRUM_PLAN = {
    0: dict(hat=38, kick=58, snare=None, clap=None, hat16=False),
    1: dict(hat=50, kick=76, snare=68, clap=None, hat16=False),
    2: dict(hat=56, kick=92, snare=88, clap=82, hat16=True),
    3: dict(hat=40, kick=66, snare=62, clap=None, hat16=False),
    4: dict(hat=56, kick=92, snare=88, clap=82, hat16=True),
    5: dict(hat=34, kick=60, snare=None, clap=None, hat16=False),
}
for s in range(N_SECTIONS):
    plan = DRUM_PLAN[s]
    evs = []
    for bar in range(BARS_PER):
        t0 = bar * BAR
        hat_step = 120 if plan["hat16"] else 240
        for k in range(0, BAR, hat_step):
            evs.append(MusicEvent(pitch=K["hat_closed"], volume=plan["hat"],
                                  start_tick=t0 + k, end_tick=t0 + k + 60))
        # kick: 1 & 3 (bar-local beats; no overflow past bar end)
        kick_beats = [0, 960]
        for kb in kick_beats:
            if t0 + kb + 120 > (bar + 1) * BAR:
                continue
            evs.append(MusicEvent(pitch=K["kick"], volume=plan["kick"],
                                  start_tick=t0 + kb, end_tick=t0 + kb + 120))
        if plan["snare"] is not None:
            for sb in (960, 2880):
                if t0 + sb + 120 > (bar + 1) * BAR:
                    continue
                evs.append(MusicEvent(pitch=K["snare"], volume=plan["snare"],
                                      start_tick=t0 + sb, end_tick=t0 + sb + 120))
        if plan["clap"] is not None:
            for sb in (960, 2880):
                if t0 + sb + 120 > (bar + 1) * BAR:
                    continue
                evs.append(MusicEvent(pitch=K["clap"], volume=plan["clap"],
                                      start_tick=t0 + sb, end_tick=t0 + sb + 120))
    phase2.set_unit(6, s, MusicUnit(events=evs))

# --- voice-leading check (bass + lead per bar pair) ---
vlc = VoiceLeadingRules(style="classical")
vl_flags = []
for bar in range(N_BARS - 1):
    s, b = divmod(bar, BARS_PER)
    root_a, qa = CHORD_INFO[bar]
    root_b, qb = CHORD_INFO[bar + 1]
    bass_a = nearest_pc_pitch(root_a % 12, 33, 52, anchor=41) or 41
    bass_b = nearest_pc_pitch(root_b % 12, 33, 52, anchor=41) or 41
    u = phase2.matrix.get_unit((0, s))
    evs = [e for e in u.events
           if e.pitch > 0 and b * BAR <= e.start_tick < (b + 1) * BAR]
    evs_next = [e for e in u.events
                if e.pitch > 0 and (b + 1) * BAR <= e.start_tick < (b + 2) * BAR]
    if evs and evs_next:
        lead_a = evs[0].pitch
        lead_b = evs_next[0].pitch
        viol = vlc.check_parallel_motion([bass_a, lead_a], [bass_b, lead_b])
        if viol:
            vl_flags.append((bar, viol))
        hid = vlc.check_hidden_fifths([bass_a, lead_a], [bass_b, lead_b])
        if hid:
            vl_flags.append((bar, hid))
print("VOICE-LEADING flags (bass+lead, classical):", len(vl_flags))


def fix_hidden_fifth(phase2, bar):
    """Nudge lead's first note of bar+1 off a hidden 5th/8ve with the bass."""
    s, b = divmod(bar + 1, BARS_PER)
    if b >= BARS_PER:
        return False
    u = phase2.matrix.get_unit((0, s))
    evs = list(u.events)
    target = None
    for e in evs:
        if e.pitch > 0 and b * BAR <= e.start_tick < (b + 1) * BAR:
            target = e
            break
    if target is None:
        return False
    root, quality = CHORD_INFO[bar + 1]
    tones = chord_tones(root, quality, lo=60, hi=88)
    if not tones:
        return False
    bass = nearest_pc_pitch(root % 12, 33, 52, anchor=41) or 41
    cands = [t for t in tones if abs((t - bass) % 12) not in (0, 7)]
    if not cands:
        return False
    target.pitch = min(cands, key=lambda c: (abs(c - target.pitch), c))
    phase2.set_unit(0, s, MusicUnit(events=evs))
    return True


n_fixed = 0
for (bar, _viol) in list(vl_flags):
    if fix_hidden_fifth(phase2, bar):
        n_fixed += 1
print("VL fixes applied:", n_fixed)

# --- normalize every cell to exact section boundary (zero-drift invariant) ---
def normalize_cell(unit, total_ticks):
    evs = list(unit.events)
    for e in evs:
        if e.end_tick > total_ticks:
            e.end_tick = total_ticks
        if e.start_tick >= total_ticks:
            e.start_tick = total_ticks - 10
        if e.start_tick < 0:
            e.start_tick = 0
        if e.end_tick <= e.start_tick and e.pitch == 0:
            e.end_tick = e.start_tick + 1
    if not evs or evs[-1].end_tick < total_ticks:
        evs.append(MusicEvent(pitch=0, volume=0,
                              start_tick=total_ticks - 1,
                              end_tick=total_ticks))
    return MusicUnit(events=sorted(evs, key=lambda e: (e.start_tick, e.pitch)))


for s in range(N_SECTIONS):
    for v in range(N_V):
        u = phase2.matrix.get_unit((v, s))
        if u is None:
            phase2.set_unit(v, s, create_empty_unit(SECTION_TICKS))
            continue
        norm = normalize_cell(u, SECTION_TICKS)
        phase2.set_unit(v, s, norm)

ok2, msg2 = phase2.validate()
print("PHASE2 validate:", msg2)
P2_MIDI = os.path.join(MIDI_DIR, "091-baroque-genetic-allemande.mid")
phase2.to_midi(P2_MIDI)
print("phase2 written", P2_MIDI)

# provenance sidecars
from workflows.provenance import write_provenance, AI_ASSISTED  # noqa: E402
write_provenance(P1_MIDI, classification=AI_ASSISTED,
                 generator="GeneticGenerator(method 003)",
                 parameters={"phase": 1, "seed": SEED,
                             "fitness": "baroque_contour",
                             "method": "003 Genetic Genome Selection"},
                 notes="Raw genetic draft: unquantized, no harmony.")
write_provenance(P2_MIDI, classification=AI_ASSISTED,
                 generator="GeneticGenerator(method 003) + rules layer",
                 parameters={"phase": 2, "seed": SEED,
                             "grid": "16th (120 @ 480 TPB)",
                             "key": "D aeolian",
                             "harmony": "011 TonalNetworkGenerator walk",
                             "method": "003 + 011 wiring"},
                 notes="Rules post-processed: grid lock, scale snap, "
                       "chord-tone quantize, voice-leading check.")

print("DONE")